version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_dev
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
