-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.User exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


password : SelectionSet (Maybe String) Api.Object.User
password =
    Object.selectionForField "(Maybe String)" "password" [] (Decode.string |> Decode.nullable)


passwordAgain : SelectionSet (Maybe String) Api.Object.User
passwordAgain =
    Object.selectionForField "(Maybe String)" "passwordAgain" [] (Decode.string |> Decode.nullable)


username : SelectionSet (Maybe String) Api.Object.User
username =
    Object.selectionForField "(Maybe String)" "username" [] (Decode.string |> Decode.nullable)
